# remap prefix from 'C-b' to 'C-w'
unbind C-b
set-option -g prefix C-w
bind C-w send-prefix

# Reload tmux configuration
bind-key r source-file ~/.dotfiles/tmux/tmux.conf \; display-message "tmux configuration reloaded"
# bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded"

# Enable mouse mode
set -g mouse on

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux display time for panes
set -g display-panes-time 5000

# Split panes using v and b
unbind '"'
unbind %
bind-key v split-window -v
bind-key b split-window -h

# Swap with window to the right, then move to that window
bind-key > swap-window -t +1 \; select-window -t +1

# Swap with window to the left, then move to that window  
bind-key < swap-window -t -1 \; select-window -t -1

# Using prefix + h/j/k/l to move between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Using prefix + H/J/K/L to swap between panes
bind-key J swap-pane -D
bind-key K swap-pane -U

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use vi keys in copy mode
set-window-option -g mode-keys vi

# Characterwise selection with v
bind-key -T copy-mode-vi v send -X begin-selection

# Linewise selection with V
bind-key -T copy-mode-vi V send -X select-line

# Blockwise selection with Ctrl-v
bind-key -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-on

# Yank selection with 'y'
bind-key -T copy-mode-vi y send -X copy-selection

# Default Terminal Mode to 256 Colors
set -g default-terminal "xterm-256color"

# Override Terminal Mode to 256 Colors
set -ga terminal-overrides ",xterm-256color:Tc"

# Pane border
set -g pane-border-style fg=green
set -g pane-active-border-style fg=green

# Status bar  
set -g status-style fg=yellow,bg=black
set -g window-status-style fg=green,bg=black
set -g window-status-current-style fg=green,bg=black,bold
set -g status-right "#(date '+%a') | #(uname -sm)"

# Message/input 
set -g message-style fg=white,bg=black,

# List of TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TPM 
run '~/.tmux/plugins/tpm/tpm'
